trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'test'

steps:
- checkout: self
  persistCredentials: true

- powershell: |
    Write-Output "Checking Azure CLI version in pipeline..."
    az --version
  displayName: 'Check Azure CLI in Pipeline'
  
- powershell: |
    Write-Output "Checking latest commit message.."

    # Kiểm tra Git có hoạt động không
    git --version
    git status

    # Lấy commit message gần nhất
    $COMMIT_MESSAGE = git log -1 --pretty=%B
    Write-Output "Latest commit message: $COMMIT_MESSAGE"

    $ORG_URL = "https://dev.azure.com/silversea21"

    # Nội dung comment trực tiếp dưới dạng JSON
    $commentJson = @(
        @{
            "op" = "add"
            "path" = "/fields/System.History"
            "value" = "Fixed bug for task $TASK_ID"
        }
    ) | ConvertTo-Json -Depth 2

    # Tìm Task ID trong format [Task#....]
    $TASK_ID_MATCH = $COMMIT_MESSAGE | Select-String -Pattern "\[Task#(\d+)\]" -AllMatches
    Write-Output "Match result: $($TASK_ID_MATCH.Matches | ForEach-Object { $_.Value })"

    if ($TASK_ID_MATCH.Matches.Count -gt 0) {
        $TASK_ID = $TASK_ID_MATCH.Matches.Groups[1].Value
        Write-Output "Found Task ID: $TASK_ID"

        # Đăng nhập vào Azure DevOps bằng PAT
        # $PAT = "8Awke4Xri2RmMEAJjrdEJNUbh8sFHCcLV81auEcR5vJ1dy7wvH3MJQQJ99BCACAAAAAnzwFcAAASAZDO1sou"
        # az devops login --organization $ORG_URL <<< $PAT
        # Đăng nhập vào Azure DevOps bằng PAT
        $Env:AZURE_DEVOPS_EXT_PAT = "8Awke4Xri2RmMEAJjrdEJNUbh8sFHCcLV81auEcR5vJ1dy7wvH3MJQQJ99BCACAAAAAnzwFcAAASAZDO1sou"

        # Gửi comment đến Task ID trong Azure DevOps
        Write-Output "Sending commit to Task ID $TASK_ID..."
        az devops invoke --area workitems --resource workItems `
        --route-parameters id=$TASK_ID `
        --http-method PATCH `
        --body "$commentJson" `
        --organization $ORG_URL

        if ($LASTEXITCODE -eq 0) {
            Write-Output "Comment successfully!"
        } else {
            Write-Output "Failed to comment on Task ID $TASK_ID."
            exit 1
        }
    } else {
        Write-Output "No Task ID found in commit message."
    }
  displayName: 'Process merge commit and comment in task ID (PowerShell)'
