# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
      include:
        - main

pool:
  name: 'test'

steps:
- script: echo "test commit and update task id"
  displayName: 'starting pipeline'

- script: |
    echo "Get commit commit..."
    git log -1 --pretty=format:"%s" > commit_message.txt
    
    echo "Extract task id from commit..."
    TASK_ID=$(grep -oP 'Task#\d+' commit_message.txt | cut -d'#' -f2)
    
    if [ -n "$TASK_ID" ]; then
        echo "Find Task ID: $TASK_ID"
        
        echo "Send commit to Task ID $TASK_ID..."
        
        az devops invoke --area workitems --resource workItems \
        --route-parameters id=$TASK_ID \
        --http-method PATCH \
        --in-file comment.json
        
        echo "Comment successfully!"
    else
        echo "Not found task id in commit."
    fi
  displayName: 'comment in task id'

- script: echo "complete pipeline"
  displayName: 'complete Pipeline'
